# ? App Name
spring.application.name=smartcontactmanager

# ? Server Port
server.port=8181

# ? MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartcontact
spring.datasource.username=root
spring.datasource.password=Rahman@786
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ? Enable JPA Repositories
spring.data.jpa.repositories.enabled=true

# ? Thymeleaf Auto Reload
spring.thymeleaf.cache=false

# ? DevTools (Auto Restart + Live Reload)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true